AWSTemplateFormatVersion: "2010-09-09"
Description: |
  Builds a network infrastructure  

Resources:
  DevVpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      Tags:
        - Key: stage
          Value: development
  
  DevSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref DevVpc
      CidrBlock: 10.0.0.0/24
      AvailabilityZone: !Select 
          - 0
          - Fn::GetAZs: !Ref "AWS::Region"
      Tags:
        - Key: Name
          Value: Development
        - Key: Department
          Value: HumanResources
  
  ProdSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref DevVpc
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select 
          - 1
          - Fn::GetAZs: !Ref "AWS::Region"
      Tags:
        - Key: Name
          Value: Production
        - Key: Department
          Value: HumanResources

  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref DevVpc
      Tags:
        - Key: Name
          Value: PrivateRouteTable

  PrivateRoute1:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      # DestinationCidrBlock: 10.0.0.0/16

  ProdRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
         RouteTableId: !Ref PrivateRouteTable
         SubnetId: !Ref ProdSubnet