AWSTemplateFormatVersion: "2010-09-09"
Description: |
  Builds a network infrastructure  

Resources:
  DevVpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      Tags:
        - Key: stage
          Value: development
  
  DevSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref DevVpc
      CidrBlock: 10.0.0.0/24
      AvailabilityZone: !Select 
          - 0
          - Fn::GetAZs: !Ref "AWS::Region"
      Tags:
        - Key: Name
          Value: Development
        - Key: Department
          Value: HumanResources
  
  ProdSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref DevVpc
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select 
          - 1
          - Fn::GetAZs: !Ref "AWS::Region"
      Tags:
        - Key: Name
          Value: Production
        - Key: Department
          Value: HumanResources

  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref DevVpc
      Tags:
        - Key: Name
          Value: PrivateRouteTable

  MyIgw:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: MyIgw
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref DevVpc
      InternetGatewayId: !Ref MyIgw

  MyKeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyFormat: pem
      KeyName: globalkp # Required
      KeyType: rsa
      Tags: 
        - Key: Name
          Value: GlobalKeyPair

  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: MySecurityGroup
      GroupDescription: Default security group for EC2 instances
      VpcId: !Ref DevVpc
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      # SecurityGroupEgress:
      #   - Security Group Rule
      Tags:
        - Key: Name
          Value: MySecurityGroup

  TestServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0fc5d935ebf8bc3bc
      KeyName: !Ref MyKeyPair
      InstanceType: t2.micro
      SecurityGroupIds:
        - !Ref MySecurityGroup
      SubnetId: !Ref ProdSubnet
      UserData: 
        Fn::Base64: |
          #!/bin/bash
          sudo apt update
          sudo apt dist-upgrade -y
          sudo apt install apache2 -y
      Tags:
        - Key: Name
          Value: TestServer

  # PrivateRoute1:
  #   Type: AWS::EC2::Route
  #   Properties:
  #     RouteTableId: !Ref PrivateRouteTable
      # DestinationCidrBlock: 10.0.0.0/16

  ProdRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
         RouteTableId: !Ref PrivateRouteTable
         SubnetId: !Ref ProdSubnet

Outputs:
  TestServerPublicIp:
    Description: Public IP of the test server
    Value: !GetAtt TestServer.PublicIp